"use client";

import { useEffect, useRef } from "react";
import Hls from "hls.js";
import Plyr from "plyr";
import "plyr/dist/plyr.css";

export const HlsPlyrHydrator = () => {
  const observerRef = useRef<MutationObserver | null>(null);

  const initializePlayer = (video: HTMLVideoElement) => {
    // Prevent double initialization
    if (video.getAttribute("data-plyr-initialized") === "true") return;

    const src = video.getAttribute("src");
    if (!src) return;

    // Mark as initialized immediately so we don't try again
    video.setAttribute("data-plyr-initialized", "true");

    // 1. Check if it is an HLS stream
    const isHls = src.endsWith(".m3u8");

    if (isHls && Hls.isSupported()) {
      const hls = new Hls();
      hls.loadSource(src);

      // Wait for HLS to parse the manifest (qualities) before building Plyr
      hls.on(Hls.Events.MANIFEST_PARSED, () => {
        const availableQualities = hls.levels.map((l) => l.height);
        // Add '0' for Auto
        availableQualities.unshift(0);

        new Plyr(video, {
          quality: {
            default: 0,
            options: availableQualities,
            forced: true,
            onChange: (newQuality: number) => {
              if (newQuality === 0) {
                hls.currentLevel = -1; // Auto
              } else {
                const levelIndex = hls.levels.findIndex((l) => l.height === newQuality);
                hls.currentLevel = levelIndex;
              }
            },
          },
          i18n: { qualityLabel: { 0: "Auto" } },
        });
      });

      hls.attachMedia(video);
    } else {
      // 2. Standard Video (mp4) or Safari Native HLS
      new Plyr(video);
    }
  };

  const checkAndHydrate = () => {
    // Find all video tags generated by Tiptap
    const videoElements = document.querySelectorAll("video.js-hls-video");

    videoElements.forEach((element) => {
      initializePlayer(element as HTMLVideoElement);
    });
  };

  useEffect(() => {
    // 1. Initial check (in case content is already there)
    checkAndHydrate();

    // 2. Set up Observer to watch for API content injection
    observerRef.current = new MutationObserver((mutations) => {
      let shouldCheck = false;
      for (const mutation of mutations) {
        if (mutation.addedNodes.length > 0) {
          shouldCheck = true;
          break;
        }
      }
      if (shouldCheck) {
        checkAndHydrate();
      }
    });

    // Start observing the body for injected HTML
    observerRef.current.observe(document.body, {
      childList: true,
      subtree: true,
    });

    return () => {
      observerRef.current?.disconnect();
    };
  }, []);

  return null;
};
