import { useSelector } from "react-redux";
import type { RootState } from "@/libs/stores";

export const useBrandAnalytic = () => {
  const {
    loadingAffiliates,
    loadingCampaigns,
    loadingContent,
    loadingContracts,
    loadingRevenueTrend,
    loadingTopProducts,
    loadingTopRatingProducts,
    loadingDashboard,
    loadingContractStatus,
    loadingTaskStatus,
    loadingRevenueOverTime,
    loadingRefundViolation,
    loadingGrossIncome,
    loadingNetIncome,
    affiliates,
    campaigns,
    content,
    contracts,
    revenueTrend,
    topProducts,
    topRatingProducts,
    dashboard,
    contractStatusDistribution,
    taskStatusDistribution,
    revenueOverTime,
    refundViolationStats,
    grossIncome,
    netIncome,
    selectedPeriod,
    customStartDate,
    customEndDate,
    trendGranularity,
  } = useSelector((state: RootState) => state.manageBrandAnalytic);
  return {
    loadingAffiliates,
    loadingCampaigns,
    loadingContent,
    loadingContracts,
    loadingRevenueTrend,
    loadingTopProducts,
    loadingTopRatingProducts,
    loadingDashboard,
    loadingContractStatus,
    loadingTaskStatus,
    loadingRevenueOverTime,
    loadingRefundViolation,
    loadingGrossIncome,
    loadingNetIncome,
    affiliates,
    campaigns,
    content,
    contracts,
    revenueTrend,
    topProducts,
    topRatingProducts,
    dashboard,
    contractStatusDistribution,
    taskStatusDistribution,
    revenueOverTime,
    refundViolationStats,
    grossIncome,
    netIncome,
    selectedPeriod,
    customStartDate,
    customEndDate,
    trendGranularity,
  };
};
