import { useSelector } from "react-redux";
import type { RootState } from "@/libs/stores";

export const useMarketingAnalytic = () => {
  const {
    loading,
    loadingKPI,
    loadingRevenue,
    loadingTopBrands,
    loadingDeadlines,
    loadingContractStatus,
    loadingTaskStatus,
    loadingRevenueOverTime,
    loadingRefundViolation,
    loadingGrossRevenue,
    loadingNetRevenue,
    loadingContractRevenueBreakdown,
    dashboard,
    activeBrands,
    activeCampaigns,
    draftCampaigns,
    monthlyRevenue,
    revenueByType,
    topBrands,
    upcomingDeadlines,
    contractStatusDistribution,
    taskStatusDistribution,
    revenueOverTime,
    refundViolationStats,
    grossRevenue,
    netRevenue,
    contractRevenueBreakdown,
    selectedPeriod,
    customStartDate,
    customEndDate,
    trendGranularity,
  } = useSelector((state: RootState) => state.manageMarketingAnalytic);
  return {
    loading,
    loadingKPI,
    loadingRevenue,
    loadingTopBrands,
    loadingDeadlines,
    loadingContractStatus,
    loadingTaskStatus,
    loadingRevenueOverTime,
    loadingRefundViolation,
    loadingGrossRevenue,
    loadingNetRevenue,
    loadingContractRevenueBreakdown,
    dashboard,
    activeBrands,
    activeCampaigns,
    draftCampaigns,
    monthlyRevenue,
    revenueByType,
    topBrands,
    upcomingDeadlines,
    contractStatusDistribution,
    taskStatusDistribution,
    revenueOverTime,
    refundViolationStats,
    grossRevenue,
    netRevenue,
    contractRevenueBreakdown,
    selectedPeriod,
    customStartDate,
    customEndDate,
    trendGranularity,
  };
};
